### ISSUE TITLE
TypeError: Cannot read property '_type' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-github-issue-notebooks#117]
I have opened a GH issue notebook from vscode repo and typed `Ctrl+Space` to bring up intellisense and was greeted with this:

```
ERR Cannot read property '_type' of undefined: TypeError: Cannot read property '_type' of undefined
	at CompletionItemProvider.provideCompletionItems (/Users/bpasero/.vscode-oss-dev/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.113/dist/extension-node.js:2082:20)
	at SuggestAdapter.provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostLanguageFeatures.js:728:54)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostLanguageFeatures.js:1641:81
	at ExtHostLanguageFeatures._withAdapter (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostLanguageFeatures.js:1375:28)
	at ExtHostLanguageFeatures.$provideCompletionItems (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/common/extHostLanguageFeatures.js:1641:25)
	at RPCProtocol._doInvokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:399:27)
	at RPCProtocol._invokeHandler (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:384:45)
	at RPCProtocol._receiveRequest (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:306:32)
	at RPCProtocol._receiveOneMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:234:26)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:115:52
	at Listener.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:418:27)
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:523:34)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:478:35)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extensionHostProcess.js:155:41
	at Listener.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:418:27)
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:523:34)
	at BufferedEmitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:478:35)
	at PersistentProtocol._receiveMessage (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:726:45)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:612:83
	at Listener.invoke (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:418:27)
	at Emitter.fire (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:523:34)
	at ProtocolReader.acceptChunk (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:269:37)
	at /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:236:61
	at Socket.listener (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:41:17)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by bpasero** [comment]
![Recording 2022-02-07 at 07 40 57](https://user-images.githubusercontent.com/900690/152737700-e6a48f56-955c-4077-b893-0be2fd7a46e2.gif)

**Comment by jrieken** [comment]
Rooted here: https://github.com/microsoft/vscode-github-issue-notebooks/blob/38d50eddcededb245a21a39171dc2b7771b1675a/src/extension/languageProvider.ts#L310
