### ISSUE TITLE
Empty notebook results in dead end experience

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-github-issue-notebooks#26]
![image](https://user-images.githubusercontent.com/35271042/81751918-4648b800-9465-11ea-94fe-4d4d52dd1274.png)

When creating a new GitHub Issues notebook, there is no cell added nor do any of the "Insert" cell commands work. This results in a dead end and a pretty bad experience.

The notebook sample extension at least always has a cell visible and doesn't let you delete it:

![image](https://user-images.githubusercontent.com/35271042/81752046-8e67da80-9465-11ea-9499-bdd2d040c422.png)

Below is the console log I see in dev tools:
```log
 ERR Cannot read property 'handle' of undefined: TypeError: Cannot read property 'handle' of undefined
    at NotebookCellList.splice2 (file:///Users/misolori/Projects/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:272:86)
    at NotebookCellList.attachViewModel (file:///Users/misolori/Projects/vscode/out/vs/workbench/contrib/notebook/browser/view/notebookCellList.js:178:22)
    at NotebookEditorWidget.attachModel (file:///Users/misolori/Projects/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:362:27)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async NotebookEditorWidget.setModel (file:///Users/misolori/Projects/vscode/out/vs/workbench/contrib/notebook/browser/notebookEditorWidget.js:252:21)
```

**Comment by jrieken** [comment]
This should not happen... The notebooks core should always create an empty cell for new notebooks...

**Comment by rebornix** [comment]
It's a regression, we lost the template cell when creating new documents.
