### ISSUE TITLE
Doesn't work; `github-issues.new` not found

### ISSUE THREAD

**Issue by gbraad** [microsoft/vscode-github-issue-notebooks#97]
Just nistalled the notebooks extensions and it doesn't work 
```
Command 'New GitHub Issue Notebook' resulted in an error (command 'github-issues.new' not found)
```

At first I thought it doesn't work due to a missing dependency, but installing 'GitHub Issues' didn't solve this.

**Comment by Hansanghyeon** [comment]
I also have the same problem.

**Comment by gbraad** [comment]
@jrieken @rebornix ping 🔔 ?

**Comment by jrieken** [comment]
Please try with latest of this extension (0.0.102). There used to be a missing activation event which has been fixed in the meantime

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/123899743-58075a80-d99a-11eb-9910-e68868e5b2fd.png)

**Comment by gbraad** [comment]
@jrieken As you can see I have tried with the latest version, but no difference

**Comment by Indlgo** [comment]
Experiencing the same problem on Intel MacOS environment (extension version v0.0.102).

And I found this log when trying to run the command for the first time. It might be one of the reasons.

```
[2021-07-14 15:10:34.418] [exthost] [error] Activating extension ms-vscode.vscode-github-issue-notebooks failed due to an error:
[2021-07-14 15:10:34.418] [exthost] [error] Error: [ms-vscode.vscode-github-issue-notebooks]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode.vscode-github-issue-notebooks
	at m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:90347)
	at Object.d [as checkProposedApiEnabled] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:90294)
	at Object.onDidChangeNotebookCells (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:40060)
	at new ProjectContainer (/Users/hgpark/.vscode/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.102/dist/extension-node.js:9746:78)
	at activate (/Users/hgpark/.vscode/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.102/dist/extension-node.js:10219:30)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14865)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14538)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12738
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

**Comment by jrieken** [comment]
this extension *must* be used with  [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by gbraad** [comment]
Is this documented?

**Comment by jrieken** [comment]
yes, in fact pretty strong

<img width="756" alt="Screen Shot 2021-07-14 at 09 31 52" src="https://user-images.githubusercontent.com/1794099/125581590-2f2656e1-fbdb-4c3f-83b5-8f7a4a29e6ab.png">

**Comment by gbraad** [comment]
Seems this still occurs. Is there a way to do feature detection and inform
the user if the extension would work?

Perhaps this should even be part of the actual extension description to
disallow/or at least promot the user about the need of insiders/or detect
the needed feature (likely implies change in vscode)
